# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to='./upload/')),
                ('isPublic', models.BooleanField()),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('isPublic', models.BooleanField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('keyword', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField(default=True)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to=b'')),
                ('isSolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('followingQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingQuestion_set', to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('tag', models.CharField(blank=True, max_length=256)),
                ('followingPerson', models.ManyToManyField(blank=True, through='question.PersonFollow', to='question.User')),
                ('followingQuestion', models.ManyToManyField(blank=True, through='question.QuestionFollow', to='question.Question')),
            ],
        ),
        migrations.AddField(
            model_name='questionfollow',
            name='questionFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='personfollow',
            name='followingPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingPerson_set', to='question.User'),
        ),
        migrations.AddField(
            model_name='personfollow',
            name='userFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
