# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to='answer')),
                ('isPublic', models.BooleanField()),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('questionDescription', models.TextField()),
                ('dataDescription', models.TextField()),
                ('solution', models.TextField()),
                ('keyword', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('reference', models.TextField(blank=True)),
                ('caseType', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attachedDescription', models.FileField(blank=True, upload_to='case')),
                ('attachedSolution', models.FileField(blank=True, upload_to='caseSolution')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('language', models.IntegerField(default=1)),
                ('courseDate', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('h_index', models.IntegerField(default=0)),
                ('course', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('isPublic', models.BooleanField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAnswer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Message')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('keyword', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField(default=True)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to='question')),
                ('isSolved', models.BooleanField(default=False)),
                ('answerNum', models.IntegerField(default=0)),
                ('attachedDescription', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('followingQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('tag', models.CharField(blank=True, max_length=256)),
                ('isActive', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('followingCase', models.ManyToManyField(blank=True, through='question.CaseFollow', to='question.Case')),
                ('followingPerson', models.ManyToManyField(blank=True, through='question.PersonFollow', to='question.User')),
                ('followingQuestion', models.ManyToManyField(blank=True, through='question.QuestionFollow', to='question.Question')),
                ('gradeAnswer', models.ManyToManyField(blank=True, to='question.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='questionfollow',
            name='questionFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='personfollow',
            name='followingPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='personfollow',
            name='userFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollower', to='question.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='question.User'),
        ),
        migrations.AddField(
            model_name='casefollow',
            name='caseFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='casefollow',
            name='followingCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Case'),
        ),
        migrations.AddField(
            model_name='case',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
