# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to='./upload/')),
                ('isPublic', models.BooleanField()),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('keyword', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('attachedFile', models.FileField(blank=True, upload_to=b'')),
                ('isSolved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('tag', models.CharField(blank=True, max_length=256)),
                ('followingPerson', models.ManyToManyField(blank=True, related_name='_user_followingPerson_+', to='question.User')),
                ('followingQuestion', models.ManyToManyField(blank=True, to='question.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
