# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='followingPerson',
            field=models.ManyToManyField(blank=True, related_name='_newuser_followingPerson_+', to='question.NewUser'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='followingQuestion',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
    ]
