# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isSolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='followingPerson',
            field=models.ManyToManyField(blank=True, to='question.User'),
        ),
    ]
