# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 11, 6, 47, 57, 359788, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
