# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160803_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
