# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160816_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
