# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='attachedDescription',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='case',
            name='attachedSolution',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
