# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20161011_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
