# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20160816_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('isPublic', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='question.User'),
        ),
    ]
