# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20160823_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('questionDescription', models.TextField()),
                ('dataDescription', models.TextField()),
                ('solution', models.TextField()),
                ('keyword', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('reference', models.TextField()),
                ('caseType', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
    ]
