# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20161011_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('language', models.IntegerField(default=1)),
                ('courseDate', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
