# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 22, 7, 13, 59, 111581, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
