# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('caseFollower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.User')),
                ('followingCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Case')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followingCase',
            field=models.ManyToManyField(blank=True, through='question.CaseFollow', to='question.Case'),
        ),
    ]
