# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
