# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20160826_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
