# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20160829_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachedDescription',
            field=models.TextField(default=''),
        ),
    ]
