# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question_attacheddescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAnswer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Message')),
            ],
        ),
    ]
