# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_messageanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='grade',
        ),
        migrations.AddField(
            model_name='user',
            name='gradeAnswer',
            field=models.ManyToManyField(blank=True, to='question.Answer'),
        ),
    ]
