# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20161207_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to='answer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='attachedSolution',
            field=models.FileField(blank=True, upload_to='case'),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to='question'),
        ),
    ]
