# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20160906_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
